export const individualPolicyPlans = [
  { name: 'Annuity Plan', description: 'Retirement income plan' },
  { name: 'Comprehensive Auto Insurance Plan', description: 'Full vehicle coverage' },
  { name: 'Third Party Auto Insurance Plan', description: 'Basic vehicle liability coverage' },
  { name: 'Enhanced Third Party Auto Insurance Plan', description: 'Extended liability coverage' },
  { name: 'Flexible Endowment Plan', description: 'Savings with life cover' },
  { name: 'Children Education Plan (CEP)', description: 'Education fund for children' },
  { name: 'Corporate Savings Investment Plan', description: 'Investment growth plan' },
  { name: 'New Income Investment Plan', description: 'Regular income generation' },
  { name: 'Education Legacy Assurance Plan', description: 'Education protection' },
  { name: 'Credit Life Policy Plan', description: 'Loan protection' },
  { name: 'Covid 19 Plan', description: 'Pandemic coverage' },
  { name: 'Personal Accident Plan', description: 'Accident coverage' },
  { name: 'Home Insurance Plan', description: 'Property protection' },
  { name: 'Travel Insurance Plan', description: 'Travel coverage' },
  { name: 'Mortgage Protection Assurance Plan', description: 'Mortgage protection' },
  { name: 'Team Assurance Plan', description: 'Group protection' },
  { name: 'Money Wise Plan', description: 'Smart savings' },
  { name: 'Life Celebration Plan', description: 'Life event coverage' },
  { name: 'Hospital Cash Plan', description: 'Daily hospital benefit' },
  { name: 'Criticare Plan', description: 'Critical illness cover' },
];

export const corporatePolicyPlans = [
  { name: 'Marine Insurance (Cargo) Plan', description: 'Cargo protection' },
  { name: 'Service Hull & Machinery Insurance', description: 'Vessel coverage' },
  { name: 'Machinery Loss of Profit (MLOP)', description: 'Business interruption' },
  { name: 'Machinery Breakdown Insurance', description: 'Equipment protection' },
  { name: 'Oil and Gas Insurance Plan', description: 'Energy sector coverage' },
  { name: 'Agric Insurance Plan', description: 'Agricultural protection' },
  { name: 'Group Life Insurance Plan', description: 'Employee life cover' },
  { name: 'Group Education Insurance Plan', description: 'Employee education fund' },
  { name: 'Fire & Special Peril Insurance Plan', description: 'Property protection' },
  { name: 'Consequential Loss Insurance Plan', description: 'Business interruption' },
  { name: 'Contractor-All-Risk Insurance Plan', description: 'Construction coverage' },
  { name: 'Electronic Equipment Policy Insurance Plan', description: 'Tech equipment cover' },
  { name: "Employer's Liability Insurance Plan", description: 'Workplace liability' },
  { name: 'Erection-All-Risk Insurance Plan', description: 'Installation coverage' },
  { name: 'Fidelity Guarantee Insurance Plan', description: 'Employee honesty cover' },
  { name: 'Goods-In-Transit Insurance Plan', description: 'Cargo protection' },
  { name: 'Fire Burglary & Insurance Plan', description: 'Property and theft cover' },
];